# Generated by Django 3.2.16 on 2023-05-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolidate_hotelogix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellogixlogin',
            name='hotelid',
        ),
        migrations.RemoveField(
            model_name='hotellogixlogin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='hotellogixlogin',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='hotellogixlogin',
            name='user',
        ),
    ]
