# Generated by Django 3.2 on 2023-05-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidate_hotelogix', '0002_auto_20230516_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='syncmanualJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, null=True)),
                ('Revenuecode', models.CharField(max_length=100, null=True)),
                ('Revenuename', models.CharField(max_length=100, null=True)),
                ('Narration', models.CharField(max_length=100, null=True)),
                ('creditAmount', models.CharField(max_length=100, null=True)),
                ('debitAmount', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
