# Generated by Django 3.2 on 2023-05-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidate_hotelogix', '0003_syncmanualjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmanualjournal',
            name='Journalnumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
