# Generated by Django 3.2 on 2023-05-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidate_hotelogix', '0004_syncmanualjournal_journalnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmanualjournal',
            name='compid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
