# Generated by Django 3.2 on 2023-05-29 07:55

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consolidate_hotelogix', '0005_syncmanualjournal_compid'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmanualjournal',
            name='Status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='syncmanualjournal',
            name='jsondata',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='syncmanualjournal',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
