# Generated by Django 3.2.16 on 2023-06-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolidate_hotelogix', '0007_auto_20230609_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synccreditlist',
            old_name='Journalnumber',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='synccreditlist',
            old_name='Narration',
            new_name='billAmount',
        ),
        migrations.RenameField(
            model_name='synccreditlist',
            old_name='Revenuecode',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='synccreditlist',
            name='Revenuename',
        ),
        migrations.RemoveField(
            model_name='synccreditlist',
            name='creditAmount',
        ),
        migrations.RemoveField(
            model_name='synccreditlist',
            name='debitAmount',
        ),
    ]
