# Generated by Django 3.2 on 2023-07-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidate_hotelogix', '0008_auto_20230609_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synccreditlist',
            name='Status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='synccreditlist',
            name='remark',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='syncmanualjournal',
            name='Status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='syncmanualjournal',
            name='remark',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
