# Generated by Django 3.2.16 on 2023-09-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidate_hotelogix', '0009_auto_20230720_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccreditlist',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='syncmanualjournal',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
