# Generated by Django 3.2 on 2023-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidate_hotelogix', '0010_auto_20230911_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmanualjournal',
            name='mjseries',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
