# Generated by Django 3.2 on 2024-01-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyExportXML', '0002_auto_20240102_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transactionlist',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionlist',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
