# Generated by Django 3.2.16 on 2023-04-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiprocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_awb',
            name='dispatch_data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
