# Generated by Django 3.2.16 on 2023-09-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellogix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellogixlogin',
            name='contact_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotellogixlogin',
            name='contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
