# Generated by Django 3.2.16 on 2023-09-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellogix', '0002_auto_20230920_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellogixlogin',
            name='walk_contact_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotellogixlogin',
            name='walk_contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
