# Generated by Django 3.2 on 2024-01-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellogix', '0003_auto_20230927_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commfailedrecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='commrecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='depositfailedrecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='depositrecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hotellogixlogin',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invoicerecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invoicerecordfailed',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymentfailedrecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='commfailedrecord',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='commrecord',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='depositfailedrecord',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hotellogixlogin',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicerecordfailed',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentfailedrecord',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='commfailedrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositfailedrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotellogixlogin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicerecordfailed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentfailedrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
