# Generated by Django 3.2 on 2024-01-06 13:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('batch', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=400, null=True)),
                ('module_type', models.CharField(max_length=100, null=True)),
                ('compid', models.CharField(max_length=100, null=True)),
                ('storecode', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=400, null=True)),
                ('batch', models.CharField(max_length=100, null=True)),
                ('module_type', models.CharField(max_length=100, null=True)),
                ('compid', models.CharField(max_length=100, null=True)),
                ('storecode', models.CharField(max_length=100, null=True)),
                ('postjson', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_no', models.CharField(max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('so_amount', models.CharField(max_length=100, null=True)),
                ('so_date', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=400, null=True)),
                ('batch', models.CharField(max_length=100, null=True)),
                ('module_type', models.CharField(max_length=100, null=True)),
                ('compid', models.CharField(max_length=100, null=True)),
                ('storecode', models.CharField(max_length=100, null=True)),
                ('postjson', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Shopify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('storename', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('transaction1', models.CharField(max_length=100, null=True)),
                ('storecode', models.CharField(max_length=100, null=True)),
                ('compid', models.CharField(max_length=100, null=True)),
                ('lastsync', models.CharField(max_length=100, null=True)),
                ('datetime1', models.CharField(max_length=100, null=True)),
                ('ccode', models.CharField(max_length=100, null=True)),
                ('ccodepre', models.CharField(max_length=100, null=True)),
                ('stage', models.CharField(default='True', max_length=100, null=True)),
                ('gst_rates', models.CharField(default='True', max_length=100, null=True)),
                ('manage_attribute', models.CharField(default='True', max_length=100, null=True)),
                ('gst_param', jsonfield.fields.JSONField(null=True)),
                ('suspense', models.CharField(default='True', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100, null=True)),
                ('module_type', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('total_record', models.CharField(max_length=100, null=True)),
                ('success_record', models.CharField(max_length=100, null=True)),
                ('fail_record', models.CharField(max_length=100, null=True)),
                ('compid', models.CharField(max_length=100, null=True)),
                ('storecode', models.CharField(max_length=100, null=True)),
                ('recordjson', jsonfield.fields.JSONField()),
            ],
        ),
    ]
