# Generated by Django 3.2 on 2024-01-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canaraSpring', '0002_auto_20240108_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='userId',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
