# Generated by Django 3.2 on 2024-01-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canaraSpring', '0003_usersettings_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='divisionid',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
