# Generated by Django 3.2.16 on 2024-01-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidationsXML', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodelsync',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='synccreditlist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='syncmanualjournal',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='xml_syncdata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='xml_userdata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='xml_usertoken',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customermodelsync',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='synccreditlist',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='syncmanualjournal',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='xml_syncdata',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='xml_userdata',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='xml_usertoken',
            name='updatad_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermodelsync',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='synccreditlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='syncmanualjournal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
