# Generated by Django 3.2 on 2024-01-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidationsXML', '0002_auto_20240108_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='xml_syncdata',
            name='filedate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
