# Generated by Django 3.2 on 2024-01-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidationsXML', '0003_xml_syncdata_filedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='xml_userdata',
            name='autoSync',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xml_userdata',
            name='clientid',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xml_userdata',
            name='clientsecret',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
