# Generated by Django 3.2 on 2024-01-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidationsXML', '0004_auto_20240116_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml_userdata',
            name='autoSync',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xml_userdata',
            name='clientid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xml_userdata',
            name='clientsecret',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
