from django.db import models

# Create your models here.

class hotellogixlogin(models.Model):
    # api_key=models.CharField(max_length=100)
    user=models.CharField(max_length=100,null=True)
    password=models.CharField(max_length=100,null=True)
    hotelid=models.CharField(max_length=100,null=True)
    branch=models.CharField(max_length=100,null=True)
    category=models.CharField(max_length=100,null=True)
    gstin=models.CharField(max_length=100,null=True)
    state=models.CharField(max_length=100,null=True)
    saveas=models.CharField(max_length=100,null=True)
    city=models.CharField(max_length=100,null=True)
    zip=models.CharField(max_length=100,null=True)
    address1=models.CharField(max_length=100,null=True)
    ledger_settings=models.JSONField()
    companyid=models.CharField(max_length=100,null=True)
    contact_code=models.CharField(max_length=100,null=True)
    contact_name=models.CharField(max_length=100,null=True)
    walk_contact_code=models.CharField(max_length=100,null=True)
    walk_contact_name=models.CharField(max_length=100,null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updatad_at=models.DateField(auto_now=True,null=True)


class depositrecord(models.Model):
    Number=models.CharField(max_length=100,null=True)
    Date=models.CharField(max_length=100,null=True)
    Narration=models.CharField(max_length=100,null=True)
    Credit_Amount=models.CharField(max_length=100,null=True)
    Debit_Amount=models.CharField(max_length=100,null=True)
    Remark=models.CharField(max_length=500,null=True)
    Status=models.CharField(max_length=100,null=True)
    companyid=models.CharField(max_length=100,null=True)
    Requested_json=models.JSONField()
    Response_json=models.JSONField()
    branchid=models.CharField(max_length=100,null=True)
    depcode=models.CharField(max_length=100,null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updatad_at=models.DateField(auto_now=True,null=True)

    
class paymentrecord(models.Model):
    Number=models.CharField(max_length=100,null=True)
    Date=models.CharField(max_length=100,null=True)
    Amount=models.CharField(max_length=100,null=True)
    Remark=models.CharField(max_length=500,null=True)
    Status=models.CharField(max_length=100,null=True)
    companyid=models.CharField(max_length=100,null=True)
    Requested_json=models.JSONField()
    Response_json=models.JSONField()
    branchid=models.CharField(max_length=100,null=True)
    paymentcode=models.CharField(max_length=100,null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updatad_at=models.DateField(auto_now=True,null=True)

    
class invoicerecord(models.Model):
    Number=models.CharField(max_length=100,null=True)
    Date=models.CharField(max_length=100,null=True)
    Customer_Name=models.CharField(max_length=100,null=True)
    Invoice_Amount=models.CharField(max_length=100,null=True)
    Due_Amount=models.CharField(max_length=100,null=True)
    Received_Amount=models.CharField(max_length=100,null=True)
    Remark=models.JSONField()
    Status=models.CharField(max_length=100,null=True)
    companyid=models.CharField(max_length=100,null=True)
    Requested_json=models.JSONField()
    Response_json=models.JSONField()
    branchid=models.CharField(max_length=100,null=True)
    invoicecode=models.CharField(max_length=100,null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updatad_at=models.DateField(auto_now=True,null=True)


class commrecord(models.Model):
    Number=models.CharField(max_length=100,null=True)
    Date=models.CharField(max_length=100,null=True)
    Amount=models.CharField(max_length=100,null=True)
    Remark=models.CharField(max_length=500,null=True)
    Status=models.CharField(max_length=100,null=True)
    companyid=models.CharField(max_length=100,null=True)
    Requested_json=models.JSONField()
    Response_json=models.JSONField()
    branchid=models.CharField(max_length=100,null=True)
    invoicecode=models.CharField(max_length=100,null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updatad_at=models.DateField(auto_now=True,null=True)

class invoicerecordfailed(models.Model):
    Number=models.CharField(max_length=100,null=True)
    Date=models.CharField(max_length=100,null=True)
    Customer_Name=models.CharField(max_length=100,null=True)
    Invoice_Amount=models.CharField(max_length=100,null=True)
    invoicecode=models.CharField(max_length=100,null=True)
    Remark=models.JSONField()
    Status=models.CharField(max_length=100,null=True)
    companyid=models.CharField(max_length=100,null=True)
    Requested_json=models.JSONField()
    Response_json=models.JSONField()
    branchid=models.CharField(max_length=100,null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updatad_at=models.DateField(auto_now=True,null=True)

class depositfailedrecord(models.Model):
    Number=models.CharField(max_length=100,null=True)
    Date=models.CharField(max_length=100,null=True)
    Narration=models.CharField(max_length=100,null=True)
    Credit_Amount=models.CharField(max_length=100,null=True)
    Debit_Amount=models.CharField(max_length=100,null=True)
    depcode=models.CharField(max_length=100,null=True)
    Remark=models.CharField(max_length=500,null=True)
    Status=models.CharField(max_length=100,null=True)
    companyid=models.CharField(max_length=100,null=True)
    Requested_json=models.JSONField()
    Response_json=models.JSONField()
    branchid=models.CharField(max_length=100,null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updatad_at=models.DateField(auto_now=True,null=True)

class paymentfailedrecord(models.Model):
    Number=models.CharField(max_length=100,null=True)
    Date=models.CharField(max_length=100,null=True)
    Amount=models.CharField(max_length=100,null=True)
    Remark=models.CharField(max_length=500,null=True)
    Status=models.CharField(max_length=100,null=True)
    paymentcode=models.CharField(max_length=100,null=True)
    companyid=models.CharField(max_length=100,null=True)
    Requested_json=models.JSONField()
    Response_json=models.JSONField()
    branchid=models.CharField(max_length=100,null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updatad_at=models.DateField(auto_now=True,null=True)

class commfailedrecord(models.Model):
    Number=models.CharField(max_length=100,null=True)
    Date=models.CharField(max_length=100,null=True)
    Amount=models.CharField(max_length=100,null=True)
    Remark=models.CharField(max_length=500,null=True)
    Status=models.CharField(max_length=100,null=True)
    invoicecode=models.CharField(max_length=100,null=True)
    companyid=models.CharField(max_length=100,null=True)
    Requested_json=models.JSONField()
    Response_json=models.JSONField()
    branchid=models.CharField(max_length=100,null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updatad_at=models.DateField(auto_now=True,null=True)